guard 'rake', :task => 'feature:run_features' do
  watch(%r{^spec/feature/(.+)\_feature\.rb$})
end

guard 'rake', :task => 'feature:run_test_suite', :run_on_start => false, :run_on_all => true do
  watch(%r{^spec/pages/(.+)\_page\.rb$})
  watch(%r{^spec/spec_helper\.rb$})
  watch(%r{^lib/(.+)\.rb$})
end
